# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  pkgs,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "bcache"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/bbb080f3-3d30-4e74-b04f-aae9e851c934";
    fsType = "bcachefs";
    options = [
      "X-mount.subdir=root"
    ];
    neededForBoot = true;
  };
  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/bbb080f3-3d30-4e74-b04f-aae9e851c934";
    fsType = "bcachefs";
    depends = [
      "/"
    ];
    options = [
      "X-mount.subdir=nix"
    ];
    neededForBoot = true;
  };
  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/bbb080f3-3d30-4e74-b04f-aae9e851c934";
    fsType = "bcachefs";
    depends = [ "/nix" ];
    options = [
      "X-mount.subdir=persist"
    ];
    neededForBoot = true;
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/5737-FC3A";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };
  systemd.services.systemd-remount-fs.serviceConfig.ExecStart = ''
    echo funny
  ''; # Remount will failed because of the stupid dependencies

  users.users.root.password = lib.mkOverride 1100 "toor";
  boot.initrd.systemd = {
    services.unlock-bcachefs--.enable = lib.mkForce false;
    services.unlock-bcachefs-nix.enable = lib.mkForce false;
    services.unlock-bcachefs-persist.enable = lib.mkForce false;
    services.rollback = {
      description = "Reset Bcachefs root subvolume to empty snapshot";
      wantedBy = [ "initrd.target" ];
      after = [ "initrd-root-device.target" ];
      before = [ "sysroot.mount" ];
      unitConfig.DefaultDependencies = "no";
      serviceConfig.Type = "oneshot";
      path = with pkgs; [ bcachefs-tools ];
      script = ''
        mkdir /btrfs_tmp
        until mount ${config.fileSystems."/".device} /btrfs_tmp
        do
          sleep 1
        done
        # Clear root subvolume should be processed here. But I don't want to do it now.
        umount /btrfs_tmp
      '';
    };
    emergencyAccess = true;
    enable = true;
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/6e8f7a22-0010-4c64-ba0f-a043c1e3b2c7"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
