name: build
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
    - run: |
        cd nixos-modules/programs/chromium
        nix profile install nixpkgs#nixfmt-rfc-style nixpkgs#sops
        ./update.sh | nixfmt > extensions.nix
        cd ../../../
        curl ${{secrets.VPN_URL}} > nixos-modules/programs/sing-box/.key
        sops encrypt --input-type binary --output-type json nixos-modules/programs/sing-box/.key > nixos-modules/programs/sing-box/key-after
        nix flake update
        git config --local user.email "3264117476@qq.com"
        git config --local user.name "github-actions[bot]"
        git add flake.lock
        git add nixos-modules/programs/chromium/extensions.nix
        git add nixos-modules/programs/sing-box/key-after
        git commit -m "Update flakes" || true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
    - run: |
        curl ${{secrets.VPN_URL}} > iso/config.yaml
        git add .
        nix build .#iso-image
    - name: Upload images artifact
      uses: actions/upload-artifact@v4
      with:
        name: Boot.iso
        path: result/iso/*
