name: build
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 16 * * *'
jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
    - run: |
        cd programs/chromium
        nix-env -iA nixos.nixfmt-rfc-style
        nix-env -iA nixos.jq
        ./update.sh | nixfmt > extensions.nix
        curl ${{secrets.VPN_URL}} > iso/config.yaml
        git add .
        nix flake update
        nix build .#iso-image
    - name: Upload images artifact
      uses: actions/upload-artifact@v4
      with:
        name: Boot.iso
        path: result/iso/*
    - run: |
        git config --local user.email "3264117476@qq.com"
        git config --local user.name "github-actions[bot]"
        rm -rf iso/config.yaml
        git add .
        git commit -m "Update flakes" || true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
